#!/usr/bin/env bash
# airgap-load.sh
# Run this script on the air-gapped machine AFTER transferring the project bundle.
# It loads pre-saved Docker images from tar archives so docker compose can start
# the stack without any network access.
#
# Usage:
#   bash scripts/airgap-load.sh
#
# Prerequisites:
#   • Docker must be installed and running
#   • airgap-bundle/images/*.tar must exist (generated by airgap-save.sh)
#
# After loading, start the stack with:
#   docker compose -f docker-compose.yml -f docker-compose.airgap.yml up -d

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
IMAGE_DIR="${ROOT_DIR}/airgap-bundle/images"

if [[ ! -d "${IMAGE_DIR}" ]]; then
  echo "ERROR: ${IMAGE_DIR} not found." >&2
  echo "       Run scripts/airgap-save.sh on an internet-connected machine first." >&2
  exit 1
fi

echo "==> [airgap-load] Loading Docker images from ${IMAGE_DIR}..."

for tar_file in "${IMAGE_DIR}"/*.tar; do
  if [[ -f "${tar_file}" ]]; then
    echo "    Loading: $(basename "${tar_file}")"
    docker load -i "${tar_file}"
  fi
done

echo ""
echo "==> [airgap-load] All images loaded successfully."
echo ""
echo "Start the stack (air-gap mode, no internet required):"
echo "  docker compose -f docker-compose.yml -f docker-compose.airgap.yml up -d"
